### PR TITLE
Fixed a bug in predicting 0-feature samples.

### PR DESCRIPTION
**Pull request by mzweilin**

### CODE REVIEW

**Comment by srndic** [comment]
Hi mzweilin,

Thanks for contributing to Hidost! I'm afraid, however, that your pull request is solving a non-existing bug. A line consisting of only the class label is perfectly legal in LibSVM format. The [LibSVM FAQ](http://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#/Q03:_Data_preparation) has a pointer to their [checkdata.py](https://github.com/cjlin1/libsvm/blob/master/tools/checkdata.py) script for input data validation. You can check with a file such as 

```
0 1:1 2:2 3:3
1 3:3 5:1
0 
1 4:2
```

that it outputs `No error.`. 

Greetings,

**Comment by mzweilin** [comment]
Hi Nedim,

The bug does exist. The previous code will not output any line for some specific files. 

Here's an example file that will reproduce the bug: http://people.virginia.edu/~wx4ed/hidost/hidost_feat_debug.pdf

**Comment by srndic** [comment]
I have just run `pdf2vals` on your file and it gives me the following output:

```
BItsPerComponent 8
Width 26
```

This is an invalid PDF file (it lacks the Catalog object), but Poppler still parses it. What `feat-extract` will output for this file depends on what is in the feature set. If the feature set lacks both of those features, no line will be output for this sample. I think this is the point you were trying to make, yesterday I misunderstood you. 

Basically, we are dealing here with a degenerate case where a sample PDF file is transformed into the zero-vector in feature space. I decided to ignore such cases at some point but I see now that it would make more sense to clearly mark them instead, so thank you for raising this issue!

I think that the diff below represents a more optimal solution. It removes the now-unnecessary variable `no_features` and results in shorter code overall. If you agree, I will close this pull request and implement this fix and if not, please point out if there is still a problem. 

``` diff
diff --git a/src/feat-extract.cpp b/src/feat-extract.cpp
index 8aa3810..5427496 100644
--- a/src/feat-extract.cpp
+++ b/src/feat-extract.cpp
@@ -109,7 +109,6 @@ void DataActionImpl::doFull(std::stringstream &databuf) {
     std::set<std::string>::const_iterator fi = DataActionImpl::features.begin();
     std::string path;
     std::stringstream ss;
-    bool no_features = true;
     // Write file class
     ss << DataActionImpl::all_files[getId()].second << ' ';
     // Parse paths
@@ -140,7 +139,6 @@ void DataActionImpl::doFull(std::stringstream &databuf) {
             } else {
                 ss << "1 ";
             }
-            no_features = false;
             fi++;
             if (fi == features.end()) {
                 goto end_of_features;
@@ -152,8 +150,7 @@ void DataActionImpl::doFull(std::stringstream &databuf) {
     // Write file name as comment
     ss << '#' << DataActionImpl::all_files[getId()].first;
     // Do not write empty lines
-    std::string line(no_features ? std::string() : ss.str());
-    while (not this->process(line)) {
+    while (not this->process(ss.str())) {
     }
 }

```

**Comment by mzweilin** [comment]
Hi Nedim,

It's my bad I didn't describe the bug properly. I believe you are more familiar with the code, so go ahead and fix it.

--Weilin

**Comment by srndic** [comment]
Fixed!

**Pull request closed without merging**
